### ISSUE TITLE
core_affinity::get_core_ids does not actually get a list of cores on linux

### ISSUE THREAD

**Issue by avl** [Elzair/core_affinity_rs#3]
The documentation for

"core_affinity::get_core_ids"

says: 
"This function tries to retrieve information on all the "cores" active on this system."

But what the function actually does is call sched_getaffinity, and check which cores the current thread is allowed to run on.

On a freshly started thread, this will typically be all cores on the machine.

However, if affinity has been set, the core_affinity::get_core_ids-function will return only the cores the current thread is allowed to run on.

I think the documentation, or the implementation should change.

(I was bitten by this. In my test-suite all but the first test that ran hade horrible performance. Turns out all but the first test actually ran with affinity = core 0 for all threads, since the first test had set the affinity for the main thread to core 0)

**Comment by duguying** [comment]
yes, i hit the problem too

**Comment by Elzair** [comment]
I have updated the documentation to make that clearer.  There are several ways to get the number of **actual** cores, but they are beyond the scope of this crate.

> There are various ways of determining the number of CPUs available on the system, including: inspecting the contents of /proc/cpuinfo; using sysconf(3) to obtain the  values  of
> the _SC_NPROCESSORS_CONF and _SC_NPROCESSORS_ONLN parameters; and inspecting the list of CPU directories under /sys/devices/system/cpu/.
