### ISSUE TITLE
core_affinity::set_for_current fails silently

### ISSUE THREAD

**Issue by barrygreengus** [Elzair/core_affinity_rs#8]
set_for_current() doesn't check the result value of sched_setaffinity or the errno after the call. 
https://docs.rs/core_affinity/latest/src/core_affinity/lib.rs.html#104
https://linux.die.net/man/2/sched_setaffinity

So if you call core_affinity::set_for_current(x) when x is a core that doesn't exist it fails silently.

set_for_current should check the result and return a Result<> or at the very least the result value

**Comment by Elzair** [comment]
The current update should have fixed this issue.
